### ISSUE TITLE
Node version.

### ISSUE THREAD

**Issue by GlamgarOnDiscord** [OutwalkStudios/discord-backup#15]
Please update your code to node 18..

Error :

pm WARN EBADENGINE Unsupported engine {
pm WARN EBADENGINE package:
'@outwalk/discord
-backup@0.5.4', pm WARN EBADENGINE required: { node: '^16', n pm: "8' }, nom WARN EBADENGINE current: { node: 'v18.16.1 , nom: '9.5.1' } pm WARN EBADENGINE }

**Comment by jleeson** [comment]
Hey @GlamgarOnDiscord, the engine requirements should now be updated with v0.5.5, if there is still an issue let me know and I can reopen this.
