### ISSUE TITLE
Bug with maxMessagesPerChannel 

### ISSUE THREAD

**Issue by SjogrenDev** [OutwalkStudios/discord-backup#19]
Hello,

The property maxMessagesPerChannel for the backup create function does not work. It always saves 100 messages for the channel.

**Comment by jleeson** [comment]
Thanks for bringing this up @SjogrenDev, It looks like there is a fetch limit of 100 for the discord request for messages in `utils.js`. This is currently in place to help prevent rate limiting since messages are fetched for each channel in the server. This is something that would require testing to ensure there is not any problems at scale when storing more than 100 messages per channel. When I have more time to work on this, I will include it in the next release.

In the meantime the `maxMessagesPerChannel` option defaults to 10 and will work up to 100 which is when the fetch limitation kicks in.

**Comment by jleeson** [comment]
`maxMessagesPerChannel` now works as expected in v0.5.9, the fetch limit is now set to the same value as `maxMessagesPerChannel`

Thanks again @SjogrenDev for bringing this to my attention.

**Comment by jleeson** [comment]
When you exceed 100 for `maxMessagesPerChannel` the following error occurs: `limit[NUMBER_TYPE_MAX]: int value should be less than or equal to 100.`

Im not sure whether or not this is something that can be changed or not, but this will require digging into the discord.js documentation for any other fetch options and perhaps restructuring the message fetching to fetch in batches. This error would explain the reason the original discord-backup package uses the 100 message limit.

@SjogrenDev Unfortunately for the time being this issue continues to not be resolved in v0.6.1

**Comment by SjogrenDev** [comment]
That's normal, if you want I can implement a feature to fetch more than 100 messages but that would cause huge backups. The original issue was that even if you used a value like 3, it would still fetch the 100 messages.

**Comment by jleeson** [comment]
Ohh I see, I misunderstood the issue initially, so the desired solution is to simply reduce the number of messages fetched if `maxMessagesPerChannel` is less than 100, in other words set the fetch limit to `(messageCount < 100 : messageCount : 100)`

Is this correct?

**Comment by SjogrenDev** [comment]
Yep, that’s correct. If you want I can add recursive message fetching to the function, it will just take more time and resources.

**Comment by SjogrenDev** [comment]
I guess I could improve this too:

Backup create options

doNotBackup: ["roles", "channels", "emojis", "bans"],
backupMembers: false,

We could remove backupMembers boolean and include it in doNotBackup.

**Comment by jleeson** [comment]
If you have a need for more than 100 messages, I would happily merge a PR for it, but I don't think its too common of a use case. Unless you want to add the recursive fetching, I can make the change by end of day. Im unsure on if we can add backupMembers to the doNotBackup array, by default members are not backed up, so for this function to work, it would need to default to true.

**Comment by SjogrenDev** [comment]
I don't think that amounts over 100 messages per channel are needed. Seems like you fixed the issue where it always saved 100 messages, so this issue can be closed.
