### ISSUE TITLE
New mode + log request

### ISSUE THREAD

**Issue by NathanLFG** [OutwalkStudios/discord-backup#2]
Hey, this module is very nice but, it's possible to add a new mode ultrafast and remove de request log on the console. Keep just the finished message.

Thanks !

**Comment by jleeson** [comment]
Hey, I didn't expect anybody to use this package so soon, but yes, I will be removing the logging in the console and as for adding an ultrafast mode, is there a speed in ms you are looking for? the fast option is 250ms, auto is 750ms and slow is 1500ms.

**Comment by jleeson** [comment]
Hey @NathanLFG, If you update to the latest version (v0.3.0) there is now no longer any request logging in the console, and several bugs have been fixed, rate limiting has also been improved. If you would still like an ultrafast mode to be added, let me know what speed you had in mind, and i can add it.

**Comment by NathanLFG** [comment]
Thank you for your answer, and for the speed I was thinking of 100 ms, I think it can already be not bad. Thanks in advance.

**Comment by jleeson** [comment]
For more flexibility, in the next update I will make some changes and add a `speed` option where you can explictly set the speed to whatever you would like, so in this case you can set it to `100`. I will update here when that update is released.

**Comment by NathanLFG** [comment]
Thank you very much, very good idea, and thank you for your reactivity on the ideas proposing!

**Comment by jleeson** [comment]
Hey @NathanLFG, you can now upgrade to v0.4.0 and I replaced the `mode` option with `speed`, instead of a string, it takes a number measured in ms.

```js
await backup.load(backupId, message.guild, { speed: 100 });
```

this should give you the desired result. Hope that helps.

**Comment by NathanLFG** [comment]
Thanks you, it's working ! And is it possible to send a message to the member when the backup has finished loading ?

**Comment by jleeson** [comment]
@NathanLFG, sending a message when it has finished is outside the scope of this module, everybody may want the message to say something else, may want it via DM or via channel message, etc. However when the backup has finished loading, you can simply send the message yourself when the promise resolves. Here is an example.

```js
try {
    await backup.load(backupId, message.guild, { speed: 100 });
    await message.author.send("Backup has been restored");
} catch (error) {
    await message.author.send(`An error occured: ${error.message}`);
}
```
