### ISSUE TITLE
DiscordAPIError[60003]: Two factor is required for this operation

### ISSUE THREAD

**Issue by SjogrenDev** [OutwalkStudios/discord-backup#30]
Hi,

Creating backups does not work when the client owner does not have 2FA, enabled.

I think that the system should check if the bot owner has 2FA enabled and then proceed to fetch information that requires 2FA.

`at async AutoModerationRuleManager._fetchMany (/home/container/node_modules/discord.js/src/managers/AutoModerationRuleManager.js:268:18)`

**Comment by jleeson** [comment]
@SjogrenDev, This should now print a warning instead of throwing an error. You can opt out of it by using the new `ignore2FA` option.

**Comment by SjogrenDev** [comment]
> @SjogrenDev, This should now print a warning instead of throwing an error. You can opt out of it by using the new `ignore2FA` option.

Thank you! Btw a similar error also happens if the bot does not have enough permissions to do certain things. Maybe add a check for that too.
